#!/bin/bash

iptables -t mangle -D fwmark
iptables -t mangle -D PREROUTING -j fwmark
iptables -t mangle -D OUTPUT -j fwmark
iptables -t mangle -D fwmark -m set --match-set warp dst -j MARK --set-mark 2
ip rule del fwmark 2 table warp
ip route del default dev wg table warp
iptables -t nat -D POSTROUTING -m mark --mark 0x2 -j MASQUERADE
ipset destroy warp
